### ISSUE TITLE
I CANT COMMIT - I NEED TO BE AN OWNER NOT MEMBER

### ISSUE THREAD

**Issue by BBroadbent** [BDO-Coding/Barren-World#1]

**Comment by danielharris0** [comment]
Danny will do it tomorrow evening

**Comment by danielharris0** [comment]
I think Danny is the best Human Being

**Comment by danielharris0** [comment]
Danny will do it tomorrow evening

On 16 Oct 2016 9:03 p.m., "Benjamin Broadbent" notifications@github.com
wrote:

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/BDO-Coding/Barren-World/issues/1, or mute the thread

**Comment by BBroadbent** [comment]
Thanks

**Comment by danielharris0** [comment]
Mason says haha

**Comment by danielharris0** [comment]
O can't fix it on my phone
